# Talking points

Assume wholesale to be customers spending over $1000 (by inspection, likely a conservative estimate)
86.8% of income from wholesale
No amazon fee confirmed
More stable income, can arrange consistent yearly transactions
81% of wholesale from UK, expand into Europe, framework already there from Netherlands and similar market
List competitors and any relevant details

Graph of wholesale by region
Graph of wholesale revenue vs retail revenue

### Intro work
What is the problem?
Sales too low vs other companies
Sales not enough in certain periods
Some products not selling well?


Why we are giving those recommendations?

How are we are going to cover this today?
Signpost recommendations then pass over to Faye

Need to point out the problem and pain to persuade (start or before recommendation)

Redo slides


### Positives
Multiple revenue streams (B2B and B2C)
Strong B2B sales
Diverse range of products


### Problems
High cost of Amazon Fee
Changing digital landscape -> reconsider marketing strategies
Competitors strong, more wholesale opportunity
Competitors are good at b2c, try and beat them at b2b
Business too reliant on UK sales

### Challenges for conclusion
Legal issues when exporting (shouldn't be too bad thanks to EU)